iExchange/config/routes.rb
Rails.application.routes.draw do
  devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "posts#index"

  namespace :admin do
    resources :posts
  end
  resources :msgs, except: [:update,:edit]
  resources :posts do
    member do
      put 'close' => 'posts#close_post'
      put 'open' => 'posts#open_post'
      put 'ban' => 'posts#ban_post'
      put 'finish' => 'posts#finish_post'
    end
    resources :comments
  end
end

iExchange/app/models/admin/post.rb
class Admin::Post < Post
end

class Admin::User < User
end

iExchange/app/models/post.rb
class Post < ActiveRecord::Base
	has_attached_file :image, styles: { medium: "300x300#", thumb: "100x100#" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  	belongs_to :user
  	has_many :comments, dependent: :destroy
end

iExchange/app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :set_admin_post, only: [:show, :destroy]
  before_action :authenticate_user!
  before_action :check_admin

  def index
    @admin_posts = Admin::Post.all
    @admin_users = Admin::User.all
  end

  def show
  end

  def destroy
    @admin_post.destroy
    redirect_to admin_posts_url, notice: '刪除成功'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_post
      @admin_post = Admin::Post.find(params[:id])
    end

    def check_admin
      if current_user.id != 1
        redirect_to root_path, notice: '非管理員無法進入管理界面'
      end     
    end


end

iExchange/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
      if params[:search]
        @post = Post.where('status = 1 AND title LIKE ?', "%#{params[:search]}%")
      elsif params[:place]
        @post = Post.where('status = 1 AND place LIKE ?', "%#{params[:place]}%") 
      else
        @post= Post.where("status = 1")
      end
  end

  def new
    @post= current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post , notice: '發表成功'
    else
      render 'new' , alert: '發表失敗'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path , notice: '刪除成功'
  end

  def show
  end

  def close_post
    @post = Post.find(params[:id])
    @post.status=2
    if @post.save
      redirect_to :back , notice: '關閉成功'
    else
      redirect_to :back , alert: '關閉失敗'
    end
  end

  def open_post
    @post = Post.find(params[:id])
    @post.status=1
    if @post.save
      redirect_to @post , notice: '開啓成功'
    else
      redirect_to :back , alert: '開啓失敗'
    end
  end

  def ban_post
    @post = Post.find(params[:id])
    @post.status=3
    if @post.save
      redirect_to @post , notice: '鎖定成功'
    else
      redirect_to :back , alert: '鎖定失敗'
    end
  end

  def finish_post
    @post = Post.find(params[:id])
    @post.status=4
    if @post.save
      redirect_to @post , notice: '確認交換完成'
    else
      redirect_to :back , alert: '確認交換失敗'
    end
  end


  private


  def find_post
    @post=Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title,:description,:itemtype,:place,:image)
  end
end

iExchange/app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

iExchange/app/helpers/posts_helper.rb
module PostsHelper
end

iExchange/app/views/admin/posts/index.html.erb
<div clas="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">管理員後台</h1><br>
      <table class="table table-bordered ">
        <thead>
          <tr>
            <th colspan="6">文章列表</th>
          </tr>
          <tr>
            <th>標題</th>
            <th>種類</th>
            <th>地點</th>
            <th>發表者</th>
            <th>狀態</th>
            <th>操作</th>
          </tr>
        </thead>

        <tbody>
          <% @admin_posts.each do |admin_post| %>
            <tr>
              <td><%= link_to admin_post.title, post_path(admin_post) %></td>
              <td><%= admin_post.itemtype %></td>
              <td><%= admin_post.place %></td>
              <td><%= admin_post.user.name %></td>
              <% if admin_post.status == 1 %>
                <td>開啓</td>
              <% elsif admin_post.status == 3 %>
                <td>鎖定</td>
              <% elsif admin_post.status == 4 %>
                <td>完成</td>
              <% else %>
                <td>關閉</td>
              <% end %>
              <td>
                <%= link_to '刪除', admin_post, method: :delete, data: { confirm: 'Are you sure?' } %>
                <% if admin_post.status == 1 %>
                  <%= link_to '關閉', close_post_path(admin_post),method: :put %>
                  <%= link_to '封鎖', ban_post_path(admin_post),method: :put %>
                <% elsif admin_post.status == 2 || admin_post.status == 3 %>
                  <% if admin_post.status == 2 %>
                    <%= link_to '封鎖', ban_post_path(admin_post),method: :put %>
                  <% end %>
                  <%= link_to '開啓', open_post_path(admin_post),method: :put %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table><br>
      <table class="table table-bordered ">
        <thead>
          <tr>
            <th colspan="3">會員列表</th>
          </tr>
          <tr>
            <th>ID</th>
            <th>名字</th>
            <th>信箱</th>
          </tr>
        </thead>
        <tbody>
          <% @admin_users.each do |admin_user| %>
            <tr>
              <td><%= admin_user.id %></td>
              <td><%= admin_user.name %></td>
              <td><%= admin_user.email %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to '返回', root_path ,:class => "btn btn-default right" %>
    </div>
  </div>
</div>