Foodmap/config/routes.rb
Rails.application.routes.draw do

  root 'stores#index'
  resources :comments, only: [:destroy] 
  resources :custom_rates, only: [:destroy] 
  resources :stores do
    resources :comments, only: [:create] 
    resources :custom_rates, only: [:create] 
  end
  get "myfood" => "stores#myfood"
  get "draw" => "stores#draw"
  get "login" => "users#login", :as => "login"
  get 'signup' => 'users#signup',:as => 'signup'
  post "create_login_session" => "users#create_login_session"
  delete "logout" => "users#logout", :as => "logout"
  resources :users, only: [:index,:create,:update,:edit] 
end

Foodmap/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :store
end

Foodmap/app/models/custom_rate.rb
class CustomRate < ActiveRecord::Base
	belongs_to :store
	belongs_to :user
end

Foodmap/app/models/store.rb
class Store < ActiveRecord::Base
	geocoded_by :address
	has_many :custom_rates, dependent: :destroy
	has_many :comments, dependent: :destroy
	belongs_to :user
	after_validation :geocode, :if => :address_changed?
    has_attached_file :image, styles: { medium: "300x300#", thumb: "100x100#" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
    validates :address, presence: true 
    validates :name, presence: true      
    
    def update_score
    	self.rate = self.custom_rates.average(:score)
    	self.save!
    end
end
 

Foodmap/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :custom_rates
	has_many :stores
	has_many :comments
	validates :email, presence: true, uniqueness: true
	validates :name, presence: true
	validates :password, presence: true, length: { minimum: 6 }
end

Foodmap/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  private
  def current_user
  	@current_user ||= session[:user_id] && User.find(session[:user_id])
  end

  def check_login
    if !current_user
      flash[:danger] = "請先登入"
      redirect_to login_path
    end
  end

  helper_method :current_user,:check_login
end

Foodmap/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@store=Store.find(params[:store_id])
  	@comment=@store.comments.new(comment_params)
  	@comment.user_id = current_user.id
  	@comment.save!
  	respond_to do |format|
  		format.html { redirect_to @comment}
  		format.js
  	end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @comment}
      format.js
    end
  end

  private
  def comment_params
  	params.require(:comment).permit(:body)
  end
end

Foodmap/app/controllers/custom_rates_controller.rb
class CustomRatesController < ApplicationController
  def create
  	@store=Store.find(params[:store_id])
  	@rates=@store.custom_rates.new(rate_params)
  	@rates.user_id = current_user.id
   	@rates.store_id = @store.id
  	@rates.save!
    @store.update_score
  	redirect_to @store
  end

  def destroy
    @rate=CustomRate.find(params[:id])
    @store=Store.find(@rate.store_id)
    @rate.destroy
    @store.update_score
    redirect_to :back
  end

  private
  def rate_params
  	params.require(:custom_rate).permit(:score)
  end
end

Foodmap/app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :check_login,only: %i[new]
  before_action :find_store, only: %i[show edit update destroy]
  before_action :check_store_owner,only: %i[edit update destroy]
  
  def index
    if params[:title] && params[:rate] && params[:foodtype]
      @store = Store.where('name LIKE ? AND rate >= ? AND foodtype = ?', "%#{params[:title]}%",params[:rate].to_i,params[:foodtype]).order(created_at: :desc)
    elsif params[:title] && params[:rate]
      @store = Store.where('name LIKE ? AND rate >= ?', "%#{params[:title]}%",params[:rate].to_i).order(created_at: :desc)
    elsif params[:title] && params[:foodtype]
      @store = Store.where('name LIKE ? AND foodtype = ?', "%#{params[:title]}%",params[:foodtype]).order(created_at: :desc)
    elsif params[:rate] && params[:foodtype]
      @store = Store.where('rate >= ? AND foodtype = ?',params[:rate].to_i,params[:foodtype]).order(created_at: :desc)
    else
      @store = Store.all.order(created_at: :desc)
    end
  end

  def create
    @store= Store.new(store_params)
    @store.user_id = current_user.id
    if @store.save
      flash[:success] = "發表成功"
      redirect_to @store 
    else
      flash[:danger] = "發表失敗"
      render 'new' 
    end
  end

  def new
    @store= Store.new
  end

  def destroy
    @store.destroy
    flash[:success] = "刪除成功"
    redirect_to root_path
  end

  def show
    if current_user 
      @userrate = @store.custom_rates.find_by_user_id(current_user.id)
    end
    @hash = Gmaps4rails.build_markers(@store) do |store, marker|
      marker.lat store.latitude
      marker.lng store.longitude
    end
    @store.view_count+=1
    @store.save
    @comments = @store.comments
  end


  def edit
  end

  def update
    if @store.update(store_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def myfood
    @store = current_user.stores
  end

  def draw
    if params[:place] && params[:rate] && params[:foodtype]
      @store = Store.where('rate >= ? AND foodtype = ? AND place = ?',params[:rate].to_i, params[:foodtype], params[:place])
      @store = @store.order("RANDOM()").first
    end
  end

  private


  def find_store
    @store=Store.find(params[:id])
  end

  def store_params
    params.require(:store).permit(:address,:foodtype,:description,:name,:longitude,:latitude,:image,:place)
  end

  def check_store_owner
    @store=Store.find(params[:id])
    if (@store.user_id != current_user.id)
      redirect_to @store
    end
  end
end

Foodmap/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_login , only: %i[edit]
  def index
    @user = current_user
    @store = current_user.stores
  end
  
  def create_login_session
    user =User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id]=user.id
      flash[:success] = "登入成功"
      redirect_to root_path 
    else
      flash[:danger] = "登入失敗"
      redirect_to :login
    end
  end

  def signup
    @user=User.new
  end

  def edit
    @user = current_user
  end

  def update
    if current_user.update(user_params)
      flash[:success] = "更新成功"
      redirect_to root_path
    else
      flash[:danger] = "更新失敗"
      redirect_to users_path
    end
  end

  def create
    user=User.new(user_params)
    if user.save
      flash[:success] = "註冊成功"
      redirect_to root_path
    else
      flash[:danger] = "註冊失敗"
      redirect_to signup_path
    end
  end

  def logout
    session[:user_id]=nil
    flash[:success] = "登出成功"
    redirect_to root_path
  end

  private
   def user_params
     params.require(:user).permit!
   end
end

Foodmap/app/helpers/application_helper.rb
module ApplicationHelper
  def distance_of_time_in_words(from_time, to_time = 0, include_seconds = false)
    from_time = from_time.to_time if from_time.respond_to?(:to_time)
    to_time = to_time.to_time if to_time.respond_to?(:to_time)
    distance_in_minutes = (((to_time - from_time).abs)/60).round
    distance_in_seconds = ((to_time - from_time).abs).round
 
    case distance_in_minutes
        when 0..1
            return (distance_in_minutes == 0) ? '不到 1 分钟' : '1 分钟' unless include_seconds
        case distance_in_seconds
            when 0..4   then '約5秒'
            when 5..9   then '約10秒'
            when 10..19 then '約20秒'
            when 20..39 then '約30秒'
            when 40..59 then '約1分鐘'
            else             '1分鐘'
        end
 
        when 2..44           then "#{distance_in_minutes}分鐘"
        when 45..89          then '約1小時'
        when 90..1439        then "大約#{(distance_in_minutes.to_f / 60.0).round}小時"
        when 1440..2879      then '1天'
        when 2880..43199     then "#{(distance_in_minutes / 1440).round}天"
        when 43200..86399    then '約1個月'
        when 86400..525599   then "#{(distance_in_minutes / 43200).round}個月"
        when 525600..1051199 then '約1年'
        else                      "#{(distance_in_minutes / 525600).round}年"
   	end
  end
end

Foodmap/app/helpers/comments_helper.rb
module CommentsHelper
end

Foodmap/app/helpers/custom_rates_helper.rb
module CustomRatesHelper
end

Foodmap/app/helpers/stores_helper.rb
module StoresHelper
end

Foodmap/app/helpers/users_helper.rb
module UsersHelper
end

Foodmap/app/views/comments/_comment.html.erb
<div class="panel panel-default" id="<%= dom_id comment %>">
  <div class="panel-heading"><%= comment.user.name %></div>
  <div class="panel-body">
    <%= comment.body %>
    <div class="btn-group pull-right">
	    <% if comment.user == current_user %>
			<%= link_to 'Destroy', comment, method: :delete,remote: true, class: "btn btn-sm btn-default" %>
		<% end %>
	</div>
  </div>
  <div class="panel-heading">由 <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> 前發表</div>
</div>

Foodmap/app/views/comments/create.js.erb
$('#comments').append("<%= j render @comment %>");
$('#comment_body').val("");

Foodmap/app/views/comments/destroy.js.erb
$('#<%= dom_id(@comment) %>').fadeOut();

Foodmap/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%=link_to 'Food', root_path , :class => 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right">
                <% if current_user %>
                    <li><%= link_to '新增店家', new_store_path %></li>
                    <li><%= link_to '我的美食地圖', myfood_path %></li>
                    <li><%= link_to '幫我決定', draw_path %></li>
                    <li><%= link_to '會員專區', users_path %></li>
                    <li><%= link_to "登出",logout_path,method: :delete %></li>
                <% else %>
                    <li><%= link_to '登入', login_path %></li>
                    <li><%= link_to '註冊', signup_path %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

Foodmap/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Food</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navbar' %>
	<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
        	<%= value %>
        	<button type="button" class="close" data-dismiss="alert">&times;</button>
        </div>
  <% end %>
	<%= yield %>

</body>
</html>

Foodmap/app/views/stores/_form.html.erb
<%= form_for @store do |f| %>
	<%= f.label :name, '店名' %>
	<%= f.text_field :name , :class =>"form-control" %><br>
	<%= f.label "地區" %><br>
	<%= f.select :place, %w[臺北 新北 基隆 桃園 新竹 台中 苗栗 嘉義 彰化 臺南 高雄 屏東 台東 花蓮 宜蘭 澎湖] , :class =>"form-control" %><br><br>
	<%= f.label :address, '地址' %>
	<%= f.text_field :address , :class =>"form-control" %><br>
	<%= f.label "類型" %><br>
	<%= f.select :foodtype, %w[中式 西式 宵夜 燒烤 早餐] , :class =>"form-control" %><br><br>
    <%= f.label "圖片" %>
    <%= f.file_field :image , :class =>"form-control" %><br>
	<%= f.label :description, '介紹' %>
	<%= f.text_area :description , :class =>"form-control" %><br>
  	<%= f.submit '建立', :class =>"btn btn-default" %>
<% end %>

Foodmap/app/views/stores/draw.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= form_tag draw_path,:class =>'form-inline ', method: :get do %>
    			<%= select_tag :place, "<option>臺北</option><option>新北</option><option>基隆</option><option>桃園</option><option>新竹</option><option>台中</option><option>苗栗</option><option>嘉義</option><option>彰化</option><option>臺南</option><option>高雄</option><option>屏東</option><option>台東</option><option>花蓮</option><option>宜蘭</option><option>澎湖</option>".html_safe,:class =>'form-control' %>
    			<%= number_field_tag :rate, params[:rate],:class =>'form-control',in: 0.0..10.0, step: 0.1,placeholder: "最低分數" %>
    			<%= select_tag :foodtype, "<option>中式</option><option>西式</option><option>宵夜</option><option>燒烤</option><option>早餐</option>".html_safe,:class =>'form-control' %>
    			<%= submit_tag "抽",:class => 'btn btn-primary' ,name: nil %>
			<% end %>
		</div>
	</div>
</div>
<% if @store %>
	<div class="container">
		<div class="row">
			<div class="col-md-4 col-md-offset-4">
				<div class="thumbnail">
					<%= link_to image_tag(@store.image.url(:medium)), @store %>
					<div class="caption">
			 			<h1 class="text-center"><%= link_to @store.name,@store %></h1>
			 			<% if @store.custom_rates.count != 0 %>
				 			<% if @store.rate <= 3 %>
				 				<p class="label label-success">分數: <%= @store.rate %></p>
				 			<% elsif @store.rate > 3 && @store.rate <=7 %> 
				 				<p class="label label-warning">分數: <%= @store.rate %></p>
							<% else %> 
				 				<p class="label label-danger">分數: <%= @store.rate %></p>
				 			<% end %>
				 		<% else %>
				 			<p class="label label-default">尚無評分</p>
				 		<% end %>
				 		<p class="label label-info"><%= @store.place %></p>
	 					<p class="label label-primary"><%= @store.view_count %> 瀏覽</p>
	 					<p class="label label-info"><%= @store.comments.count %>留言</p>
			 		</div>
				</div>
			</div>
		</div>
	</div>
<% end %>

Foodmap/app/views/stores/edit.html.erb
<div class="container" >
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= render 'form' %>
		</div>
	</div>
</div>

Foodmap/app/views/stores/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
				<%= form_tag stores_path,:class =>'form-inline ', method: :get do %>
					<span>搜尋:</span>
    				<%= text_field_tag :title, params[:title],:class =>'form-control', placeholder: "標題" %>
    			    <%= number_field_tag :rate, params[:rate], in: 0.0..10.0, step: 0.1,:class =>'form-control', placeholder: "最低分" %>
    			    <%= select_tag :foodtype, "<option>中式</option><option>西式</option><option>宵夜</option><option>燒烤</option><option>早餐</option>".html_safe,:class =>'form-control'%>
    			    <%= submit_tag "送出",:class => 'btn btn-primary' ,name: nil %>
				<% end %>
		</div>
	</div>
	<% @store.each_slice(3) do |stores| %>
		<div class="row">
			<% stores.each do |store| %>
				<div class="col-md-4">
					<div class="thumbnail">
						<%= link_to image_tag(store.image.url(:medium)), store %>
						<div class="caption">
 							<h1 class="text-center"><%= link_to store.name,store %></h1>
 							<% if store.custom_rates.count != 0 %>
	 							<% if store.rate <= 3 %>
	 								<p class="label label-success">分數: <%= store.rate %></p>
	 							<% elsif store.rate > 3 && store.rate <=7 %> 
	 								<p class="label label-warning">分數: <%= store.rate %></p>
								<% else %> 
	 								<p class="label label-danger">分數: <%= store.rate %></p>
	 							<% end %>
	 						<% else %>
	 							<p class="label label-default">尚無評分</p>
	 						<% end %>
	 						<p class="label label-info"><%= store.place %></p>
	 						<p class="label label-primary"><%= store.view_count %> 瀏覽</p>
	 						<p class="label label-info"><%= store.comments.count %>留言</p>
 						</div>
					</div>
				</div>
			<% end %>
		</div>
	<% end %>
</div>

Foodmap/app/views/stores/myfood.html.erb
<div class="container">
	<% @store.each_slice(3) do |stores| %>
		<div class="row">
			<% stores.each do |store| %>
				<div class="col-md-4">
					<div class="thumbnail">
						<%= link_to image_tag(store.image.url(:medium)), store %>
						<div class="caption">
 							<h1><%= link_to store.name,store %></h1>
 							<% if store.custom_rates.count != 0 %>
	 							<% if store.rate <= 3 %>
	 								<p class="label label-success">分數: <%= store.rate %></p>
	 							<% elsif store.rate > 3 && store.rate <=7 %> 
	 								<p class="label label-warning">分數: <%= store.rate %></p>
								<% else %> 
	 								<p class="label label-danger">分數: <%= store.rate %></p>
	 							<% end %>
	 						<% else %>
	 							<p class="label label-default">尚無評分</p>
	 						<% end %>
 						</div>
					</div>
				</div>
			<% end %>
		</div>
	<% end %>
</div>

Foodmap/app/views/stores/new.html.erb
<div class="container" >
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= render 'form' %>
		</div>
	</div>
</div>

Foodmap/app/views/stores/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<%= image_tag(@store.image.url(:medium), class: "store_img") %>
			<table class="table text-center table-bordered">
				<tr>
					<th colspan="4" class="text-center store_title"><%= @store.name %></th>
				</tr>
				<tr>
					<th class="text-center" colspan="2">作者</th>
					<td colspan="2"><%= @store.user.name %></td>
				</tr>
				<tr>
					<th class="text-center" colspan="2">地址</th>
					<td colspan="2"><%= @store.address %></td>
				</tr>
				<tr>
					<th class="text-center">地區 </th>
					<td><%= @store.place %></td>
					<th class="text-center">類型 </th>
					<td><%= @store.foodtype %></td>
				</tr>
				<tr>
					<% if @store.rate %>
						<th class="text-center" colspan="2">平均</th>
						<td colspan="2"><%= @store.rate %> 共 <%= @store.custom_rates.count %> 人評分</td>
					<% else %>
						<td colspan="4">尚未有人評分</td>
					<% end %>
				</tr>
				<% if current_user %>
				<tr>
					<% if @userrate == nil %>
						<td colspan="4">
							<%= form_for [ @store , @store.custom_rates.new ] do |f| %>
								<%= f.number_field(:score, in: 0.0..10.0, step: 0.1) %>
								<%= f.submit '評分',:class => "btn btn-default", remote: true %>
							<% end %>
						</td>
					<% else %>
				   		<td colspan="4">
				   			已經評分了 給予 <%= @userrate.score %> 分
				   			<%= link_to '收回', @userrate ,   method: :delete  %>
				   		</td>
					<% end %>
				</tr>
				<% end %>
			</table>
			<div class="panel panel-default" >
				<div class="panel-heading">介紹</div>
			  	<div class="panel-body">
			    	<%= @store.description %>
			  	</div>
			</div>
		</div>
		<div class="col-md-6 text-center">
  			<div id="map" style='width:100%; height: 400px;'></div><br>
			<% if current_user %>
				<% if current_user.id == @store.user_id %>
					<div class="btn-group" role="group">
					  	<%= link_to '刪除', store_path,:class => "btn btn-default", method: :delete, data: {confirm: "Are you sure?" } %>
						<%= link_to '編輯', edit_store_path ,:class => "btn btn-default" %>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div id="comments">
				<%= render @comments %>
			</div>
			<% if current_user %>
				<%= form_for [ @store , @store.comments.new ], remote: true do |f| %>
					<%= f.text_area :body ,:class=>"form-control" %><br>
					<%= f.submit '發表',:class => "btn btn-default" %>
				<% end %>
			<% else %>
				<p class="text-center">請先<%= link_to '登入',login_path %></p>
			<% end %>
		</div>
	</div>
</div>
<script type="text/javascript">
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
	  markers = handler.addMarkers(<%=raw @hash.to_json %>);
	  handler.bounds.extendWith(markers);
	  handler.fitMapToBounds();
	});
	
</script>

Foodmap/app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<h1 class="text-center">您發的文</h1>
			<table class="table text-center table-bordered">
				<tr>
					<th>名稱</th>
					<th>評分</th>
					<th>留言數</th>
					<th>操作</th>
				</tr>
				<% @store.each do |store| %>
					<tr>
						<td><%= store.name %></td>
						<td><%=store.rate %></td>
						<td><%=store.comments.count %></td>
						<td>
							<%= link_to '編輯', edit_store_path(store) %>
							<%= link_to '刪除', store_path(store),method: :delete %>
						</td>
					</tr>
				<% end %>
			</table>
		</div>

		<div class="col-md-6">
			<h1 class="text-center">會員資料</h1>
			<%= form_for @user do |f| %>
			  <%= f.label :name, '用戶名' %>
			  <%= f.text_field :name , :class =>"form-control" %><br>
			  <%= f.label :email, '信箱' %>
			  <%= f.text_field :email , :class =>"form-control" %><br>
			  <%= f.label :password, '新密碼' %>
			  <%= f.password_field :password,:class =>"form-control" %><br>
			  <%= f.label :password_confirmation, '確認密碼' %>
			  <%= f.password_field :password_confirmation, :class =>"form-control" %><br>
			  <%= f.submit '更新', :class =>"btn btn-default" %>
			<% end %>
		</div>
	</div>
</div>

Foodmap/app/views/users/login.html.erb
<div class="container" >
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= form_tag "create_login_session" do %>
				<%= label_tag "信箱" %>
				<%= text_field_tag :email ,params[:email], :class =>"form-control"  %>
				<%= label_tag "密碼" %>
				<%= password_field_tag :password, params[:password], :class =>"form-control"  %><br>
				<%= submit_tag "登錄", :class =>"btn btn-default" %>
			<% end %>
		</div>
	</div>
</div>

Foodmap/app/views/users/signup.html.erb
<div class="container" >
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= form_for @user do |f| %>
			  <%= f.label :name, '用戶名' %>
			  <%= f.text_field :name , :class =>"form-control" %><br>
			  <%= f.label :email, '信箱' %>
			  <%= f.text_field :email , :class =>"form-control" %><br>
			  <%= f.label :password, '密碼' %>
			  <%= f.password_field :password,:class =>"form-control" %><br>
			  <%= f.label :password_confirmation, '確認密碼' %>
			  <%= f.password_field :password_confirmation, :class =>"form-control" %><br>
			  <%= f.submit '註冊', :class =>"btn btn-default" %>
			<% end %>
		</div>
	</div>
</div>