iExchange/config/routes.rb
Rails.application.routes.draw do
  devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "posts#index"

  namespace :admin do
    resources :posts
  end
  resources :msgs, except: [:update,:edit]
  resources :posts do
    member do
      put 'close' => 'posts#close_post'
      put 'open' => 'posts#open_post'
      put 'ban' => 'posts#ban_post'
      put 'finish' => 'posts#finish_post'
    end
    resources :comments
  end
end

iExchange/app/views/layouts/_footer.html.erb
<footer class="section section-primary">
    <div>
       MADE BY Bver49
    </div>
</footer>

iExchange/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to('iExchange', root_path,:class => "navbar-brand") %>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to '發表文章',new_post_path %></li>
                <% if user_signed_in? %>
                    <% if current_user.id==1 %>
                        <li><%= link_to '管理員後台', admin_posts_path %></li>
                    <% end %>
                    <li><%= link_to '我的帳戶', edit_user_registration_path  %></li>
                    <li><%= link_to '寄信', new_msg_path  %></li>
                    <li>
                        <% if (check_msg > 0) %>
                            <%= link_to msgs_path do %>
                                收件匣 <span class="badge"><%= check_msg %></span>
                            <% end %>                        
                        <% else %>
                            <%= link_to '收件匣' ,msgs_path %>
                        <% end %>
                    </li>
                    <li><%= link_to '登出', destroy_user_session_path , :method => :delete %></li>
                <% else %>
                    <li><%= link_to '註冊',new_user_registration_path  %></li>
                    <li><%= link_to '登入',new_user_session_path %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

iExchange/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>iExchange</title>
  <meta charset="utf-8" >
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<div class="container">
  <div class="col-md-12">
<% flash.each do |key, value| %>
  <% alert_class = case key
                   when :notice then "success"
                   when :alert then "danger"
                   else "success"
                   end %>
  <%= content_tag :div, class: "alert alert-#{alert_class}" do %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= value %>
  <% end %>
<% end %>
  </div>
</div>

<%= yield %>
<div style="display:block; height:300px;"></div>
<%= render 'layouts/footer' %>

</body>
</html>