iExchange/config/routes.rb
Rails.application.routes.draw do
  devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "posts#index"

  namespace :admin do
    resources :posts
  end
  resources :msgs, except: [:update,:edit]
  resources :posts do
    member do
      put 'close' => 'posts#close_post'
      put 'open' => 'posts#open_post'
      put 'ban' => 'posts#ban_post'
      put 'finish' => 'posts#finish_post'
    end
    resources :comments
  end
end

iExchange/app/models/admin/post.rb
class Admin::Post < Post
end

class Admin::User < User
end

iExchange/app/models/post.rb
class Post < ActiveRecord::Base
	has_attached_file :image, styles: { medium: "300x300#", thumb: "100x100#" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  	belongs_to :user
  	has_many :comments, dependent: :destroy
end

iExchange/app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :set_admin_post, only: [:show, :destroy]
  before_action :authenticate_user!
  before_action :check_admin

  def index
    @admin_posts = Admin::Post.all
    @admin_users = Admin::User.all
  end

  def show
  end

  def destroy
    @admin_post.destroy
    redirect_to admin_posts_url, notice: '刪除成功'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_post
      @admin_post = Admin::Post.find(params[:id])
    end

    def check_admin
      if current_user.id != 1
        redirect_to root_path, notice: '非管理員無法進入管理界面'
      end     
    end


end

iExchange/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
      if params[:search]
        @post = Post.where('status = 1 AND title LIKE ?', "%#{params[:search]}%")
      elsif params[:place]
        @post = Post.where('status = 1 AND place LIKE ?', "%#{params[:place]}%") 
      else
        @post= Post.where("status = 1")
      end
  end

  def new
    @post= current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post , notice: '發表成功'
    else
      render 'new' , alert: '發表失敗'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path , notice: '刪除成功'
  end

  def show
  end

  def close_post
    @post = Post.find(params[:id])
    @post.status=2
    if @post.save
      redirect_to :back , notice: '關閉成功'
    else
      redirect_to :back , alert: '關閉失敗'
    end
  end

  def open_post
    @post = Post.find(params[:id])
    @post.status=1
    if @post.save
      redirect_to @post , notice: '開啓成功'
    else
      redirect_to :back , alert: '開啓失敗'
    end
  end

  def ban_post
    @post = Post.find(params[:id])
    @post.status=3
    if @post.save
      redirect_to @post , notice: '鎖定成功'
    else
      redirect_to :back , alert: '鎖定失敗'
    end
  end

  def finish_post
    @post = Post.find(params[:id])
    @post.status=4
    if @post.save
      redirect_to @post , notice: '確認交換完成'
    else
      redirect_to :back , alert: '確認交換失敗'
    end
  end


  private


  def find_post
    @post=Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title,:description,:itemtype,:place,:image)
  end
end

iExchange/app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

iExchange/app/helpers/posts_helper.rb
module PostsHelper
end

iExchange/app/views/posts/_form.html.erb
<%= form_for(@post,class: 'form-horizontal') do |f| %>
	<p>
		<%= f.label "標題" %>
		<%= f.text_field :title , :class =>"form-control" %>
	</p><br>
	<p>
		<%= f.label "描述" %>
		<%= f.text_area :description , :class =>"form-control" %>
	</p><br>	
	<p>
		<%= f.label "上傳圖片" %>
		<%= f.file_field :image , :class =>"form-control" %>
	</p><br>
	<p>
		<%= f.label "地區" %>&emsp;:&emsp;
		<%= f.select :place, %w[臺北 桃園 台中 台南 高雄 澎湖 金門 新北 宜蘭 花蓮 台東] , :class =>"form-control" %>
	</p><br>	
	<p>
		<%= f.label "交換的類別" %>&emsp;:&emsp;
		<%= f.select :itemtype, %w[服務 技能 物品] , :class =>"form-control" %>
	</p><br>
	<p>
		<%= f.submit '發表' , :class => 'btn btn-default right' %>
	</p>
<% end %>

iExchange/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

iExchange/app/views/posts/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1 class="text-center">編輯文章</h1>
			<%= render 'form' %>
		</div>
	</div>
</div>

iExchange/app/views/posts/index.html.erb
<div class="container">
	<div class="col-md-10 col-md-offset-1">
		<div class="jumbotron">
  			<h1>iExchange</h1><br>
  			<p>交換愛 / 愛交換</p>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div id="search_field">
				<h1 class="post_title">搜尋:&emsp;</h1>
				<%= form_tag posts_path,:class =>'search_form' , method: :get do %>
    				<%= text_field_tag :search, params[:search], placeholder: "Search..." %>
				<% end %>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<ol class="breadcrumb">
				<li><%= link_to '新北',posts_path(:place => '新北') %></li>
  				<li><%= link_to '臺北',posts_path(:place => '臺北') %></li>
  				<li><%= link_to '桃園',posts_path(:place => '桃園') %></li>
  				<li><%= link_to '台中',posts_path(:place => '台中') %></li>
  				<li><%= link_to '嘉義',posts_path(:place => '嘉義') %></li>
  				<li><%= link_to '台南',posts_path(:place => '台南') %></li>
  				<li><%= link_to '高雄',posts_path(:place => '高雄') %></li>
  				<li><%= link_to '澎湖',posts_path(:place => '澎湖') %></li>
			</ol>
		</div>
	</div>
</div>

<div class="container">
	<% @post.each_slice(3) do |post| %>
		<div class="row">
			<% post.each do |post| %>
				<div class="col-md-4">
					<div class="thumbnail">
						<%= link_to image_tag(post.image.url(:medium)), post %>
						<div class="caption">
 							<h1 class="post_title"><%= link_to post.title,post %></h1>
							<p><%= post.itemtype %></p>           			
            			</div>
					</div>
				</div>
			<% end %>
		</div>
	<% end %>
</div>

iExchange/app/views/posts/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1 class="text-center">新增文章</h1><br>
			<%= render 'form' %>
		</div>
	</div>
</div>

iExchange/app/views/posts/show.html.erb
<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="content" >
                  <%= image_tag @post.image.url(:medium) %>
                  <p>由<%= @post.user.name %> 發表</p>
                  <div class="btn-group" role="group">
                      <% if @post.user == current_user %>
                        <%= link_to '刪除', post_path,:class => "btn btn-default", method: :delete, data: {confirm: "Are you sure?" } %>
                        <%= link_to '編輯', edit_post_path ,:class => "btn btn-default" %>
                        <% if @post.status == 1 %>
                            <%= link_to '關閉', close_post_path(@post) ,method: :put, :class => "btn btn-default" %>
                        <% else %>
                            <%= link_to '開啓', open_post_path(@post) ,method: :put, :class => "btn btn-default" %>
                        <% end %>
                      <% else %>
                            <%= link_to '寄信給作者', new_msg_path(:receive => @post.user.email),:class => "btn btn-default"  %> 
                      <% end %>
                      <%= link_to '返回', root_path , :class => "btn btn-default" %>
                  </div>
                </div>
            </div>
            <div class="col-md-6">
                <h1><%= @post.title %></h1>
                <p class="label label-default"><%= @post.place %></p>
                <p class="label label-primary"><%= @post.itemtype %></p><br><br>
                <p><%= @post.description %></p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <h3 class="comments_title"><%= @post.comments.count %> 則留言</h3>
                <div id="comments">
                    <%= render :partial => @post.comments %>
                </div>
                <% if user_signed_in? %>
                  <%= simple_form_for [@post, Comment.new]  do |f| %>
                    <div class="field">
                        <%= f.text_area :body, class: "form-control" %>
                    </div>
                    <br>
                    <%= f.submit "Add Comment", class: "btn btn-primary" %>
                  <% end %>
                <% else %>
                    <p>請先<%= link_to '登入',new_user_session_path %></p>
                <% end %>
            </div>
        </div>
    </div>
</div>